### ISSUE TITLE
Params collapsed on save

### ISSUE THREAD

**Issue by AlexxNB** [orcuntuna/guvercin#11]
When I try to save request like this:
![изображение](https://user-images.githubusercontent.com/10389013/120275370-dd272300-c2b9-11eb-8778-d70d20041390.png)

And then try to reopen this I get request with last eneterd param only:

![изображение](https://user-images.githubusercontent.com/10389013/120275513-19f31a00-c2ba-11eb-8369-f2d725fe4cb0.png)

**Comment by orcuntuna** [comment]
Hi! @AlexxNB, we are working on the second version of guvercin app. with this update, we will add team, environment variables, documentation, and sync collections features. for this reason we are not developing the current version but we can accept PR if you want to develop.
